--- #YAML:1.0
name:               WWW-Compete
version:            0.03
abstract:           Simple OO interface for retrieving site rank, traffic stats, and trust rating from www.compete.com
author:
    - Chris Mills <cmills@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    LWP::UserAgent:  0
    XML::Simple:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
